### ISSUE TITLE
typo in title name (throughout documentation)

### ISSUE THREAD

**Issue by linboynton** [rbtl-fs22/rbtl-fs22-data#1]
https://github.com/rbtl-fs22/rbtl-fs22-data/blob/a7751d70525ecfc2ced91bf46582e821f889afbe/CITATION.cff#L46

I think there is a typo in the title name - It should be Raw dat*a* right?

**Comment by larnsce** [comment]
Thank you so much for opening this issue! I will fix it before making it public.
